"""Initial schema with site_id and email

Revision ID: 85ff3c9aa920
Revises: 
Create Date: 2025-06-13 23:19:43.900943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85ff3c9aa920'
down_revision = None
branch_labels = None
depends_on = None




def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.PrimaryKeyConstraint('company_id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('permissions',
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('permission_id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('roles',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint('role_id'),
        sa.UniqueConstraint('name')
    )
    op.create_table('sites',
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=False),
        sa.Column('longitude', sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_sites_company_id'),
        sa.PrimaryKeyConstraint('site_id')
    )
    op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=50), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=True),
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_users_company_id'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='fk_users_role_id'),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('username')
    )
    op.create_table('audit_logs',
        sa.Column('log_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_audit_logs_company_id'),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='fk_audit_logs_user_id'),
        sa.PrimaryKeyConstraint('log_id')
    )
    op.create_table('blueprints',
        sa.Column('blueprint_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('file_url', sa.String(length=255), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('uploaded_by', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_blueprints_company_id'),
        sa.PrimaryKeyConstraint('blueprint_id')
    )
    op.create_table('daily_reports',
        sa.Column('report_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('manpower', sa.Integer(), nullable=False),
        sa.Column('safety_activities', sa.Text(), nullable=True),
        sa.Column('progress_notes', sa.Text(), nullable=True),
        sa.Column('reported_by', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_daily_reports_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_daily_reports_site_id'),
        sa.PrimaryKeyConstraint('report_id')
    )
    op.create_table('documents',
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('file_url', sa.String(length=255), nullable=False),
        sa.Column('version', sa.Integer(), nullable=False),
        sa.Column('uploaded_at', sa.DateTime(), nullable=True),
        sa.Column('uploaded_by', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_documents_company_id'),
        sa.PrimaryKeyConstraint('document_id')
    )
    op.create_table('employees',
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('email', sa.String(length=100), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.Column('phone', sa.String(length=20), nullable=True),
        sa.Column('contact', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_employees_company_id'),
        sa.PrimaryKeyConstraint('employee_id'),
        sa.UniqueConstraint('email')
    )
    op.create_table('equipment',
        sa.Column('equipment_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('last_maintenance_date', sa.Date(), nullable=True),
        sa.Column('next_maintenance_date', sa.Date(), nullable=False),
        sa.Column('maintenance_notes', sa.Text(), nullable=True),
        sa.Column('site_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_equipment_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_equipment_site_id'),
        sa.PrimaryKeyConstraint('equipment_id')
    )
    op.create_table('incidents',
        sa.Column('incident_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('type', sa.String(length=50), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('severity', sa.String(length=20), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('reported_by', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_incidents_company_id'),
        sa.PrimaryKeyConstraint('incident_id')
    )
    op.create_table('inventory',
        sa.Column('inventory_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('item_name', sa.String(length=100), nullable=False),
        sa.Column('category', sa.String(length=50), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('reorder_point', sa.Integer(), nullable=False),
        sa.Column('unit_price', sa.Float(), nullable=True),
        sa.Column('location', sa.String(length=100), nullable=True),
        sa.Column('site_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_inventory_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_inventory_site_id'),
        sa.PrimaryKeyConstraint('inventory_id')
    )
    op.create_table('orders',
        sa.Column('order_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('item', sa.String(length=100), nullable=False),
        sa.Column('quantity', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('vehicle_id', sa.Integer(), nullable=True),
        sa.Column('comments', sa.Text(), nullable=True),
        sa.Column('rating', sa.Integer(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_orders_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_orders_site_id'),
        sa.PrimaryKeyConstraint('order_id')
    )
    op.create_table('permits',
        sa.Column('permit_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('permit_type', sa.String(length=100), nullable=False),
        sa.Column('issue_date', sa.Date(), nullable=False),
        sa.Column('expiry_date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_permits_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_permits_site_id'),
        sa.PrimaryKeyConstraint('permit_id')
    )
    op.create_table('projects',
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('start_date', sa.Date(), nullable=False),
        sa.Column('end_date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_projects_company_id'),
        sa.PrimaryKeyConstraint('project_id')
    )
    op.create_table('role_permissions',
        sa.Column('role_id', sa.Integer(), nullable=False),
        sa.Column('permission_id', sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(['permission_id'], ['permissions.permission_id'], name='fk_role_permissions_permission_id'),
        sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name='fk_role_permissions_role_id'),
        sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.create_table('safety_audits',
        sa.Column('audit_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('audit_date', sa.Date(), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_safety_audits_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_safety_audits_site_id'),
        sa.PrimaryKeyConstraint('audit_id')
    )
    op.create_table('subcontractors',
        sa.Column('subcontractor_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('agreement_status', sa.String(length=20), nullable=False),
        sa.Column('payment_status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_subcontractors_company_id'),
        sa.PrimaryKeyConstraint('subcontractor_id')
    )
    op.create_table('vehicles',
        sa.Column('vehicle_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_vehicles_company_id'),
        sa.PrimaryKeyConstraint('vehicle_id')
    )
    op.create_table('weather',
        sa.Column('weather_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('site_id', sa.Integer(), nullable=False),
        sa.Column('date', sa.Date(), nullable=False),
        sa.Column('temperature', sa.Float(), nullable=False),
        sa.Column('condition', sa.String(length=100), nullable=False),
        sa.Column('precipitation', sa.Integer(), nullable=False),
        sa.Column('wind_speed', sa.Float(), nullable=False),
        sa.Column('warning', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_weather_company_id'),
        sa.ForeignKeyConstraint(['site_id'], ['sites.site_id'], name='fk_weather_site_id'),
        sa.PrimaryKeyConstraint('weather_id')
    )
    op.create_table('blueprint_comments',
        sa.Column('comment_id', sa.Integer(), nullable=False),
        sa.Column('blueprint_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('comment_text', sa.Text(), nullable=False),
        sa.Column('commented_at', sa.DateTime(), nullable=True),
        sa.Column('commenter', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['blueprint_id'], ['blueprints.blueprint_id'], name='fk_blueprint_comments_blueprint_id'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_blueprint_comments_company_id'),
        sa.PrimaryKeyConstraint('comment_id')
    )
    op.create_table('inductions',
        sa.Column('induction_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('induction_type', sa.String(length=100), nullable=False),
        sa.Column('completion_date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_inductions_company_id'),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_inductions_employee_id'),
        sa.PrimaryKeyConstraint('induction_id')
    )
    op.create_table('licenses',
        sa.Column('license_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('license_type', sa.String(length=100), nullable=False),
        sa.Column('issue_date', sa.Date(), nullable=False),
        sa.Column('expiry_date', sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_licenses_company_id'),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_licenses_employee_id'),
        sa.PrimaryKeyConstraint('license_id')
    )
    op.create_table('milestones',
        sa.Column('milestone_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='fk_milestones_project_id'),
        sa.PrimaryKeyConstraint('milestone_id')
    )
    op.create_table('payments',
        sa.Column('payment_id', sa.Integer(), nullable=False),
        sa.Column('subcontractor_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('milestone', sa.String(length=100), nullable=False),
        sa.Column('amount', sa.Float(), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_payments_company_id'),
        sa.ForeignKeyConstraint(['subcontractor_id'], ['subcontractors.subcontractor_id'], name='fk_payments_subcontractor_id'),
        sa.PrimaryKeyConstraint('payment_id')
    )
    op.create_table('project_assignments',
        sa.Column('assignment_id', sa.Integer(), nullable=False),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('role', sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_project_assignments_employee_id'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='fk_project_assignments_project_id'),
        sa.PrimaryKeyConstraint('assignment_id')
    )
    op.create_table('tasks',
        sa.Column('task_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('due_date', sa.Date(), nullable=False),
        sa.Column('assigned_to', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(['assigned_to'], ['employees.employee_id'], name='fk_tasks_assigned_to'),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_tasks_company_id'),
        sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name='fk_tasks_project_id'),
        sa.PrimaryKeyConstraint('task_id')
    )
    op.create_table('timesheets',
        sa.Column('timesheet_id', sa.Integer(), nullable=False),
        sa.Column('employee_id', sa.Integer(), nullable=False),
        sa.Column('company_id', sa.Integer(), nullable=False),
        sa.Column('clock_in', sa.DateTime(), nullable=False),
        sa.Column('clock_out', sa.DateTime(), nullable=True),
        sa.Column('break_duration', sa.Integer(), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('approved_by', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['company_id'], ['companies.company_id'], name='fk_timesheets_company_id'),
        sa.ForeignKeyConstraint(['employee_id'], ['employees.employee_id'], name='fk_timesheets_employee_id'),
        sa.PrimaryKeyConstraint('timesheet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timesheets')
    op.drop_table('tasks')
    op.drop_table('project_assignments')
    op.drop_table('payments')
    op.drop_table('milestones')
    op.drop_table('licenses')
    op.drop_table('inductions')
    op.drop_table('blueprint_comments')
    op.drop_table('weather')
    op.drop_table('vehicles')
    op.drop_table('subcontractors')
    op.drop_table('safety_audits')
    op.drop_table('role_permissions')
    op.drop_table('projects')
    op.drop_table('permits')
    op.drop_table('orders')
    op.drop_table('inventory')
    op.drop_table('incidents')
    op.drop_table('equipment')
    op.drop_table('employees')
    op.drop_table('documents')
    op.drop_table('daily_reports')
    op.drop_table('blueprints')
    op.drop_table('audit_logs')
    op.drop_table('users')
    op.drop_table('sites')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('companies')
    # ### end Alembic commands ###

    # ### end Alembic commands ###
